### ISSUE TITLE
Async rendering?

### ISSUE THREAD

**Issue by okwolf** [jorgebucaran/hyperapp#682] opened 2018-04-24 05:24 UTC
Not sure if this one was on anyone's radar yet, but it's [coming soon to React](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html), so I figured I might as well ask.

It's my belief that if we decided to go async for our rendering in the future then apps built with Hyperapp best practices should still be able to work. Views should already be pure, and with the changes coming in 2.0 that will become even more so. Since lifecycle events are defined on the virtual DOM and not stateful components, they need not be run until all the DOM manipulations are committed, so side effects will only be run against a consistently-updated browser DOM.

The one area where I'm not sure if things would fall apart is with regards to interop. Could calling actions/`dispatch` from the outside world while async rendering was still happening cause bad side effects? It seems like with the right batching/queuing strategy any negative impacts of this could be mitigated.

As for whether implementing this feature would have any useful benefits or not, I'm unsure. 🤔

**Comment by russoturisto** [comment] 2018-04-25 00:09
Beginner question:

Does async rendering mean that VDOM generation (running the view/component code) would be done in a web worker?

Thanks, :)

**Comment by jorgebucaran** [comment] 2018-04-25 02:15
@russoturisto No, it doesn't mean that. It generally means that patching would be async (see <samp>patch()</samp> in the source code).

In 1.0 state updates are immediate (there is no reason for it to be otherwise), but our view redraws are async. This is because updating the state 100 times in a row should only cause one redraw.

Now, if patching was async, then we would be able to "call" actions inside the view, components or lazy components and expect state updates triggered by those actions (whether they are sync or not) to not destroy the work <samp>patch()</samp> has completed up to that point.

In 2.0 you won't be able to "call" actions as we transition from relatively pure views to immaculate views, so I don't think this is useful going forward.

**Comment by russoturisto** [comment] 2018-04-25 03:54
Understood, thank you for the explanation. :)

**Comment by jorgebucaran** [comment] 2018-08-31 14:36
@okwolf I am still not sure if the concept of async rendering will be relevant in V2 and after, but I am not closed to the idea.

**Comment by jcubic** [comment] 2019-04-19 23:30
I'm working on an experiment when I use lisp in JavaScript with hyperapp, I'm trying to write all the code in lisp but in my javascript lisp backquote return a promise instead of a value. So my app don't work because view is async. The value is resolved instantly but it's still a promise.

Do you plan of creating async rendering? I may as well update my lips to not return promise if values are not a promise, but was wondering if you plan to have it in 2.0?

**Comment by jorgebucaran** [comment] 2019-04-20 06:03
@jcubic Using Lisp in JavaScript with Hyperapp? **Nice**. You were doing just fine until you said promises! You don't need promises to accomplish anything with Hyperapp. I can't see the connection. Pre-V1 used to support actions that return promises, but that was before I learned to walk. V1's render loop uses setTimeout and V2's render loop uses requestAnimationFrame. I briefly considered using Promise-based micro tasks, but [it was problematic](https://github.com/jorgebucaran/hyperapp/commit/c7ae927d4fefb4f125a27ce61aec9894445c74be).  What async rendering refers to are asynchronous DOM updates, or the ability to update the DOM a bit, defer control back to the app, and resume updating the DOM at a later point in time. Never say never, but I'm probably never adding that to Hyperapp. We'll see. I'm skeptical that's useful at all. 

But I heard about time-slicing, suspense, high/low-priority updates, fibers? Optimizing for an impermissibly large DOM tree is a dead-end. [Style calculations](https://developers.google.com/web/fundamentals/performance/rendering/reduce-the-scope-and-complexity-of-style-calculations), and [browser reflow](https://developers.google.com/speed/docs/insights/browser-reflow), alone will make your application slow and utterly useless. That's your bottleneck. Fix that. Instead of optimizing for an absurdly large DOM tree, we optimize for real-world use cases. 

Hyperapp's reconciliation/patch algorithm consists of a single immutable pass. Async rendering involves one or more passes and generating patch objects (or "fibers" in React land](https://github.com/acdlite/react-fiber-architecture)), whereas we apply all detected changes immediately.

Update your lisp experiment to not return a promise.

**Closed by jorgebucaran** 2019-04-20 06:03 UTC
Labels: Discussion

**Comment by jcubic** [comment] 2019-04-24 18:46
The issue I was having is like this, you have view function and one the elements that render the view is asynchronous like function `getTitle()` that fetch title from server. The problem would be in my lisp, because If I use `async` function (function that return a promise) whole expression will be a promise so the view function in fact will also return a promise and whole rendering would fail.

Why not just allow promises to be returned from view function?

it's should be simple, just:

```javascript
if (isPromise(result)) {
    return result.then(render);
} else {
    return render(result);
}
```

and updating rest of the code. In my lisp code I have few places like that (even recently refactored this to function `unpromise`) and because of that I can run `(print (concat "title is " (getTitle)))` but If I put this into view it will break.

Is they a workaround to make promise work with view function?

**Comment by okwolf** [comment] 2019-04-24 23:44
The view is not the right place for fetching data from the server, it's a pure function of `state => VDOM`.

Impure/async logic should happen inside [FX](https://github.com/jorgebucaran/hyperapp/issues/750) that dispatch [actions](https://github.com/jorgebucaran/hyperapp/issues/749) to update `state` which will then use your `view` to synchronously render the populated state.

**Comment by jorgebucaran** [comment] 2019-04-25 05:26
> @jcubic Is there a workaround to make promise work with view function?

No, there isn't, and that's a benefit. The problem is likely in your program design relying on promises.

Since you are using Lisp, and even [wrote your own](https://github.com/jcubic/lips), I don't need to convince you that a pure function is preferable to one that is not. And there isn't much I can add to what @okwolf already said. Hyperapp views are pure functions receiving some state as input and producing a virtual DOM representation as output. No scoping, binding, this, async/await, promises, callbacks, observables, reactive expressions, reactive assignments, reactive declarations, subclassing, hooks, mutations, global state, or side effects.

**Comment by jcubic** [comment] 2019-04-25 07:19
@jorgebucaran @okwolf Thanks for explanation, will try to use FX then. When I was going to sleep last night I've realized that there are async actions in one of the examples (in version 1), and thought that this maybe the way to go with async code.

Thanks again and for this awesome micro framework.
