### ISSUE TITLE
V2 not working well for checkbox

### ISSUE THREAD

**Issue by diontools** [jorgebucaran/hyperapp#769] opened 2018-10-16 08:38 UTC
V2 does not update `input.checked` attribute. Is there a mistake in my code?

Example code: https://codesandbox.io/embed/k5jk439x7o

![hav2c](https://user-images.githubusercontent.com/12995573/47001981-b64a6b80-d166-11e8-9445-c518d197d471.png)

code:
```js
import * as v2 from "./hyperapp-v2";
import * as v1 from "hyperapp";

const SetCheck = (state, { checked }, ev) => {
  ev.preventDefault();
  return { ...state, checked: checked };
};

v2.app({
  init: { checked: false },
  view: state =>
    v2.h("div", {}, [
      v2.h("input", {
        type: "checkbox",
        checked: state.checked,
        onClick: [SetCheck, { checked: !state.checked }]
      }),
      state.checked ? "checked" : "unchecked"
    ]),
  container: document.getElementById("v2")
});

v1.app(
  { checked: false },
  {
    setCheck: ({ checked, ev }) => state => {
      ev.preventDefault();
      return { checked: checked };
    }
  },
  (state, actions) =>
    v1.h("div", {}, [
      v1.h("input", {
        type: "checkbox",
        checked: state.checked,
        onclick: ev => actions.setCheck({ checked: !state.checked, ev })
      }),
      state.checked ? "checked" : "unchecked"
    ]),
  document.getElementById("v1")
);
```

html:
```html
v2
<div id="v2"></div>
v1
<div id="v1"></div>
```

Thank you for reading

**Comment by zaceno** [comment] 2018-10-16 08:46
There seems to be interference from `ev.preventDefault()` in the v2 example. But I'm not sure why that would be. The order in which things happen should be the same.

**Comment by diontools** [comment] 2018-10-16 15:10
Timing of render seems to be different.
v2: Promise.resolve().then(render)
v1: setTimeout(render)

Forcing use of setTimeout solves this problem.

hyperapp-v2.js:
```js
var resolved = typeof Promise === "function" && Promise.resolve()
resolved = undefined // force disable Promise
```

**Comment by jorgebucaran** [comment] 2018-10-16 15:16
@diontools You are calling `preventDefault()` inside your `SetCheck` action. Why?

**Comment by diontools** [comment] 2018-10-17 03:58
@jorgebucaran I'm trying not to make a difference from the state by the checkbox default behavior. So I disabled the checkbox default behavior by `preventDefault()`. Perhaps I'm thinking too much. 😆

**Comment by jorgebucaran** [comment] 2018-10-17 04:06
@diontools Correct me if I'm wrong, but Hyperapp or not, why would one use `preventDefault` in the click event handler of a check input? 🤔 

And as you correctly pointed out, using `setTimeout` works because of how V2 replaces the previous `setTimeout`-based `render` with an immediately resolved Promise. I wonder if I should get rid of that and go back to V1's approach.

cc @zaceno @frenzzy @selfup

**Comment by diontools** [comment] 2018-10-17 06:08
@jorgebucaran The reason I used the `preventDefault()` is to ensure that the checkbox is changed by a change in the state only. (It's like one-way binding)

```
ideal:
  click checkbox
  -> state changing action (state.checked = true)
  -> render (input.checked = state.checked)

actual(v1):
  click checkbox
  -> input.checked = true
  -> preventDefault()
  -> state changing action (state.checked = true)
  -> input.checked = false (by preventDefault)
  -> render (input.checked = state.checked)

actual(v2):
  click checkbox
  -> input.checked = true
  -> preventDefault()
  -> state changing action (state.checked = true)
  -> render (input.checked = state.checked)
  -> input.checked = false (by preventDefault)
```

I will give up this. This is a small problem. I think that it is not necessary to use setTimeout in exchange for performance.

The fundamental problem is that the checkbox has no `readonly` attribute. 😭 
Thank you for your response!

**Comment by jorgebucaran** [comment] 2018-10-17 06:32
> @diontools I used the preventDefault() is to ensure that the checkbox is changed by a change in the state only. (It's like one-way binding)

Do you want to toggle the input check programmatically? If that's so, you can do this.


```jsx
h("input", {
  type: "checkbox",
  checked: state.checked,
  onClick: [SetCheck, { checked: state.checked }]
})
```

This will make the `checked` property reflect the value of `state.checked` even if the user clicks it. Now you can add a button or another UI element to toggle `state.checked` so that the input check can change accordingly. Here is a fork of your sandbox <https://codesandbox.io/s/lqj409pj9>.

**Comment by zaceno** [comment] 2018-10-17 06:43
@jorgebucaran 

checked: **!** state.checked

 (your fork breaks the checkbox 😉)  

... and looks like the OP already had that part figured out. 

The problem is `preventDefault`  works for checkboxes in v1, but not in v2. I guess because of the render timing -- *but I don't get it*. It shouldn't matter. If we preventDefault the browser should not touch the checkbox so, regardless of render timing, it should work.

That is also the point of using preventDefault, btw: only have one actor (Hyperapp) fiddle with the checkbox.

**Comment by jorgebucaran** [comment] 2018-10-17 06:44
@zaceno The OP said "...to ensure that the checkbox is changed by a change in the state only". So, I did that on purpose. They want the check to change only when the state changes, not when the user clicks in the check.

**Comment by zaceno** [comment] 2018-10-17 06:46
@jorgebucaran Yes but the intent was to have the state change when you click the check, right? And that state change (*not* the browser) would then cause the checkbox to become checked.

**Comment by jorgebucaran** [comment] 2018-10-17 06:48
@zaceno Sorry, no disrespect, but I have no idea what you are talking about. :)

**Comment by zaceno** [comment] 2018-10-17 07:31
@jorgebucaran, yes I understand the difference in render timing. But what I don’t understand is how preventDefault makes the difference in the v2 example working or not. PreventDefault should not change anything about render timing. All it does afaik is prevent the default browser reaction to the click - why would that affect the outcome?

**Comment by jorgebucaran** [comment] 2018-10-17 07:34
@zaceno Without doing any research, I suspect `preventDefault` outcome is async so it happens after we return from the action, update the state and render the DOM. I could be wrong!

**Comment by frenzzy** [comment] 2018-10-17 07:48
Can you make it works with native DOM? http://jsfiddle.net/d2hqmct7/

**Comment by jorgebucaran** [comment] 2018-10-17 07:50
@frenzzy In this instance V2 behaves like your fiddle, so, more like the native DOM, whereas V1 does not.

**Comment by zaceno** [comment] 2018-10-17 09:49
Yes @frenzzy s fiddle was good to see. It's still completely befuddling to me why `event.preventDefault()` breaks the checkbox. But at least we know that this behavior is the same in native js/dom as in v2. So nothing to be concerned about wrt Hyperapp.

**Comment by diontools** [comment] 2018-10-17 09:52
@jorgebucaran  I'm sorry to make you confused by my poor English.

I was hoping for a perfect synchronization of state and checkbox. I always wanted to change input.checked by action.
Clicking the checkbox changes input.checked by the browser. At this moment, the state and input.checked will be different values.

In v1, I used `preventDefault()` to prevent input.checked from being changed by the browser.
I understood that this technique is no longer needed as it is render in the onclick event in V2.

The solution is to remove `preventDefault()` from the `SetCheck` action.
```js
const SetCheck = (state, { checked }, ev) => {
  return { ...state, checked: checked };
};
```

Thank you for your help. 👍

**Comment by zaceno** [comment] 2018-10-17 09:57
@diontools @jorgebucaran I think I worked out why preventDefault breaks the state toggle. 

I believe it comes down to how preventDefault is implemented for checkboxes (and is probably a bug in webkit based browsers, at least)

It looks like when you've called preventDefault it not only prevents the browser from toggling the `checked` property: it prevents **any** tampering with the `checked` property – including programmatically `checkbox.checked = state` . This condition remains, it seems for the duration of the tick. 

Hence: this works:  http://jsfiddle.net/d2hqmct7/

**Comment by jorgebucaran** [comment] 2018-10-17 10:03
Quite interesting @zaceno 

@diontools No worries! 👋

**Comment by jorgebucaran** [comment] 2018-10-17 12:34
Forgot this was already resolved. So, closing!

**Closed by jorgebucaran** 2018-10-17 12:34 UTC
Labels: Inquiry
