### ISSUE TITLE
Adding Lazy during application execution causes JS error: Uncaught TypeError

### ISSUE THREAD

**Issue by tetradice** [jorgebucaran/hyperapp#884] opened 2019-10-07 17:07 UTC
If Lazy is not displayed at the initial launch of the app and Lazy is added when state is updated, the following error occurs.

```
index.js:357 Uncaught TypeError: Cannot read property 'view' of undefined
    at propsChanged (index.js:357)
    at getVNode (index.js:362)
    at patch (index.js:273)
    at patch (index.js]:289)
    at render (index.js:471)
```

- [CodeSandbox Example](https://codesandbox.io/s/hyperapp-lazy-bug-rm18c?fontsize=14&module=%2Fsrc%2Findex.jsx)

### Example code (JSX)

```jsx
import { h, app, Lazy } from "hyperapp";

const Label = ({ name }) => {
  return `Hello, ${name}!`;
};

const LazyLabel = () => <Lazy view={Label} name="Lazy hyperapp" />;

const LazyFlagFlip = state => !state;

app({
  init: false,
  view: state => {
    return (
      <div>
        <p>{state ? <LazyLabel /> : <Label name="hyperapp" />}</p>
        <p>
          <input type="checkbox" onchange={LazyFlagFlip} /> Lazy ON
        </p>
      </div>
    );
  },
  node: document.getElementById("app")
});
```

**Comment by sergey-shpak** [comment] 2019-10-08 21:17
@tetradice fix is already there waiting for approval or changes if needed

**Comment by tetradice** [comment] 2019-10-08 22:47
@sergey-shpak Great! Thank you for the quick fix. 🙌

**Comment by jorgebucaran** [comment] 2019-11-10 10:18
@okwolf discovered this commit introduces a perf regression in `Lazy`.

Now, I just need to understand what was this about.

**Comment by sergey-shpak** [comment] 2019-11-11 19:46
@jorgebucaran @okwolf is there any repo to run perf test?

**Comment by okwolf** [comment] 2019-11-12 01:55
@sergey-shpak you should setup to run the baseline with `2.0.3` here: https://github.com/krausest/js-framework-benchmark/tree/master/frameworks/keyed/hyperapp

When I made a copy of `frameworks/keyed/hyperapp` and added `Lazy` the perf doesn't improve and the regression occurred during `2.0.2`. This morning I manually updated `getVNode` to this and the perf of select row improved again:
```
var getVNode = function(newVNode, oldVNode) {
  return newVNode.type === LAZY_NODE
    ? ((!oldVNode ||
        !oldVNode.lazy ||
        propsChanged(oldVNode.lazy, newVNode.lazy)) &&
        ((oldVNode = newVNode.lazy.view(newVNode.lazy)).lazy = newVNode.lazy),
      oldVNode)
    : newVNode
}
```

**Comment by jorgebucaran** [comment] 2019-11-12 02:26
@okwolf By the way, is there any difference between the original one and the one with conditional lazy support `!oldVNode.lazy ||`?

**Comment by okwolf** [comment] 2019-11-12 04:00
@jorgebucaran which one is the original one? Are you asking to test the code below?

```js
var getVNode = function(newVNode, oldVNode) {
  return newVNode.type === LAZY_NODE
    ? ((!oldVNode ||
        propsChanged(oldVNode.lazy, newVNode.lazy)) &&
        ((oldVNode = newVNode.lazy.view(newVNode.lazy)).lazy = newVNode.lazy),
      oldVNode)
    : newVNode
}
```

**Comment by jorgebucaran** [comment] 2019-11-12 04:01
@okwolf I was asking if both are just as fast.

**Comment by okwolf** [comment] 2019-11-12 04:15
@jorgebucaran looks like both are the same speed ± margin of error

**Comment by sergey-shpak** [comment] 2019-11-12 11:06
@okwolf ok thanks, trying to setup and run `js-framework-benchmark`, but it looks pretty weird to me that `typeof vnode === "object"` has performance impact in general, maybe there is some additional circumstances (like Lazy view returning string and hyperapp creates textNode each time, instead of 'doing nothing' etc)

**Comment by sergey-shpak** [comment] 2019-12-22 23:50
@jorgebucaran @okwolf looks I found the root case of the performance issue, it comes from https://github.com/jorgebucaran/hyperapp/issues/905, lazy view was re-rendered each time state changed (basically it didn't work as lazy), after https://github.com/jorgebucaran/hyperapp/pull/906 is merged we can run performance tests once more

**Comment by sergey-shpak** [comment] 2020-01-14 11:49
https://github.com/jorgebucaran/hyperapp/pull/906 merged, can we close the issue?

**Closed** 2020-01-14 12:44 UTC
Labels: Performance
